import { z } from "zod";

export const teachingQuestionContentSchema = z.object({
  findingId: z.string().min(1),
  difficulty: z.enum(["easy", "medium", "hard"]),
  gradeBand: z.enum(["grades-1-5", "grades-6-8", "grades-9-12"]),
  questionType: z.enum(["find-it", "plan-it", "execute-it"]),
  codeExcerpt: z.string().min(1).max(1200),
  language: z.literal("python"),
  prompt: z.string().min(1),
  choices: z.array(z.string().min(1).max(180)).length(4),
  answer: z.string().min(1),
  hint: z.string().min(1),
  example: z.string().min(1),
  explanation: z.string().min(1),
  recap: z.string().min(1),
  actionLabel: z.string().min(1),
  beforeCode: z.string().min(1),
  afterCode: z.string().min(1),
  proposedFix: z.string().min(1),
  reanalysisEvidence: z.string().min(1),
});

export type TeachingQuestionContent = z.infer<
  typeof teachingQuestionContentSchema
> & { answers: string[] };

const easy = "grades-1-5" as const;
const medium = "grades-6-8" as const;
const hard = "grades-9-12" as const;

/**
 * The teaching demo is deliberately authored, finite, and read-only. These
 * twenty questions describe the twenty intentional Python issues in the
 * bundled fixture; gameplay never executes or edits this file.
 */
export const teachingQuestionContent = {
  "py-easy-01": {
    findingId: "py-easy-01",
    difficulty: "easy",
    gradeBand: easy,
    questionType: "find-it",
    language: "python",
    codeExcerpt: `def greet(name)\n    return "Hi " + name`,
    prompt: "What is missing after the function line?",
    choices: ["A colon :", "A comma ,", "A question mark ?", "A dollar sign $"],
    answer: "A colon :",
    hint: "Python uses a tiny mark at the end of a function line.",
    example: `def say_hi():\n    return "Hi"`,
    explanation:
      "A colon tells Python that the indented function body starts next.",
    recap: "A function definition ends with a colon.",
    actionLabel: "Water the punctuation plant",
    beforeCode: `def greet(name)\n    return "Hi " + name`,
    afterCode: `def greet(name):\n    return "Hi " + name`,
    proposedFix: "Add the missing colon.",
    reanalysisEvidence:
      "The syntax finding disappears after the corrected excerpt is reviewed.",
  },
  "py-easy-02": {
    findingId: "py-easy-02",
    difficulty: "easy",
    gradeBand: easy,
    questionType: "find-it",
    language: "python",
    codeExcerpt: `def add(a, b):\nreturn a + b`,
    prompt: "What should move under the function?",
    choices: [
      "The return line should be indented",
      "The function name should be deleted",
      "The plus sign should be a picture",
      "Nothing should change",
    ],
    answer: "The return line should be indented",
    hint: "The body of a Python function sits a little to the right.",
    example: `def double(number):\n    return number * 2`,
    explanation: "Indentation shows Python which lines belong to the function.",
    recap: "Indent the body of a function.",
    actionLabel: "Trim the indentation hedge",
    beforeCode: `def add(a, b):\nreturn a + b`,
    afterCode: `def add(a, b):\n    return a + b`,
    proposedFix: "Indent the return statement by four spaces.",
    reanalysisEvidence:
      "The indentation finding is cleared by the proposed fix.",
  },
  "py-easy-03": {
    findingId: "py-easy-03",
    difficulty: "easy",
    gradeBand: easy,
    questionType: "execute-it",
    language: "python",
    codeExcerpt: `score = 10\nprint(scor)`,
    prompt: "Which spelling should print the value?",
    choices: ["score", "scored", "scores", "Score"],
    answer: "score",
    hint: "Use the exact name created on the first line.",
    example: `pets = 3\nprint(pets)`,
    explanation:
      "Variable names must match exactly, including spelling and capitalization.",
    recap: "Use the same variable name every time.",
    actionLabel: "Water the variable plant",
    beforeCode: `score = 10\nprint(scor)`,
    afterCode: `score = 10\nprint(score)`,
    proposedFix: "Use the variable name `score`.",
    reanalysisEvidence: "The unknown-variable finding is no longer present.",
  },
  "py-easy-04": {
    findingId: "py-easy-04",
    difficulty: "easy",
    gradeBand: easy,
    questionType: "find-it",
    language: "python",
    codeExcerpt: `print("Welcome)`,
    prompt: "Which mark closes the text?",
    choices: ["A matching quote", "A colon :", "A bracket ]", "A slash /"],
    answer: "A matching quote",
    hint: "Text that starts with a quote needs the matching quote at the end.",
    example: `print("Welcome")`,
    explanation: "The closing quote tells Python where the text ends.",
    recap: "Text needs matching quotation marks.",
    actionLabel: "Water the quote flower",
    beforeCode: `print("Welcome)`,
    afterCode: `print("Welcome")`,
    proposedFix: "Add the missing closing quote.",
    reanalysisEvidence: "The unterminated-string finding is resolved.",
  },
  "py-easy-05": {
    findingId: "py-easy-05",
    difficulty: "easy",
    gradeBand: easy,
    questionType: "plan-it",
    language: "python",
    codeExcerpt: `age = 10\nif age > 5\n    print("big kid")`,
    prompt: "What belongs at the end of the if line?",
    choices: ["A colon :", "A period .", "A comma ,", "Nothing"],
    answer: "A colon :",
    hint: "A decision line also opens an indented block.",
    example: `if sunny:\n    print("play")`,
    explanation:
      "Python uses a colon before the indented lines controlled by an if.",
    recap: "If statements use a colon before their body.",
    actionLabel: "Tend the decision bed",
    beforeCode: `if age > 5\n    print("big kid")`,
    afterCode: `if age > 5:\n    print("big kid")`,
    proposedFix: "Add the colon to the if statement.",
    reanalysisEvidence: "The missing-colon finding is cleared.",
  },
  "py-easy-06": {
    findingId: "py-easy-06",
    difficulty: "easy",
    gradeBand: easy,
    questionType: "execute-it",
    language: "python",
    codeExcerpt: `colors = ["red", "blue"]\nprint(colors[2])`,
    prompt: "Which index safely chooses the second color?",
    choices: ["1", "2", "0", "3"],
    answer: "1",
    hint: "Python starts counting list positions at zero.",
    example: `pets = ["cat", "dog"]\nprint(pets[1])`,
    explanation: "The first item is at zero, so the second item is at one.",
    recap: "Python lists start counting at zero.",
    actionLabel: "Water the list bed",
    beforeCode: `print(colors[2])`,
    afterCode: `print(colors[1])`,
    proposedFix: "Use index 1 for the second item.",
    reanalysisEvidence: "The list-index finding is resolved.",
  },
  "py-easy-07": {
    findingId: "py-easy-07",
    difficulty: "easy",
    gradeBand: easy,
    questionType: "find-it",
    language: "python",
    codeExcerpt: `def welcome(name):\n    message = "Hi " + name`,
    prompt: "What does this function need to give back?",
    choices: [
      "A return statement",
      "A new file",
      "A loop forever",
      "A comment only",
    ],
    answer: "A return statement",
    hint: "A function can send a value back to the caller.",
    example: `def square(n):\n    return n * n`,
    explanation: "A return statement sends the message out of the function.",
    recap: "Return sends a function result back.",
    actionLabel: "Grow the missing return",
    beforeCode: `message = "Hi " + name`,
    afterCode: `message = "Hi " + name\n    return message`,
    proposedFix: "Return the message from the function.",
    reanalysisEvidence: "The missing-return finding is cleared.",
  },
  "py-easy-08": {
    findingId: "py-easy-08",
    difficulty: "easy",
    gradeBand: easy,
    questionType: "plan-it",
    language: "python",
    codeExcerpt: `for number in [1, 2, 3]\n    print(number)`,
    prompt: "What punctuation starts the loop body?",
    choices: ["A colon :", "A semicolon ;", "A comma ,", "A hashtag #"],
    answer: "A colon :",
    hint: "Loops open an indented group just like if statements.",
    example: `for pet in pets:\n    print(pet)`,
    explanation: "The colon marks the start of the indented loop body.",
    recap: "For loops use a colon before their body.",
    actionLabel: "Mow the loop path",
    beforeCode: `for number in [1, 2, 3]\n    print(number)`,
    afterCode: `for number in [1, 2, 3]:\n    print(number)`,
    proposedFix: "Add the colon to the for line.",
    reanalysisEvidence: "The loop syntax finding is resolved.",
  },
  "py-easy-09": {
    findingId: "py-easy-09",
    difficulty: "easy",
    gradeBand: easy,
    questionType: "execute-it",
    language: "python",
    codeExcerpt: `name = "Maya"\nprint("Hello, " + nme)`,
    prompt: "Which choice fixes the name?",
    choices: ["name", "names", "Maya", "Name"],
    answer: "name",
    hint: "Look at the variable made on the first line.",
    example: `name = "Lee"\nprint(name)`,
    explanation:
      "The code should use the variable named `name`, not a different spelling.",
    recap: "Small spelling differences can break a program.",
    actionLabel: "Tend the name plant",
    beforeCode: `print("Hello, " + nme)`,
    afterCode: `print("Hello, " + name)`,
    proposedFix: "Match the variable spelling.",
    reanalysisEvidence: "The name-reference finding disappears.",
  },
  "py-easy-10": {
    findingId: "py-easy-10",
    difficulty: "easy",
    gradeBand: easy,
    questionType: "find-it",
    language: "python",
    codeExcerpt: `message = "Good morning"\nprint(message`,
    prompt: "What is missing at the end?",
    choices: [
      "A closing parenthesis )",
      "A colon :",
      "A second print",
      "An import",
    ],
    answer: "A closing parenthesis )",
    hint: "The print call opens with a parenthesis.",
    example: `print(message)`,
    explanation:
      "Every opening parenthesis in this call needs its matching closing parenthesis.",
    recap: "Match opening and closing parentheses.",
    actionLabel: "Clip the missing bracket",
    beforeCode: `print(message`,
    afterCode: `print(message)`,
    proposedFix: "Close the print call.",
    reanalysisEvidence: "The unmatched-parenthesis finding is cleared.",
  },
  "py-medium-01": {
    findingId: "py-medium-01",
    difficulty: "medium",
    gradeBand: medium,
    questionType: "plan-it",
    language: "python",
    codeExcerpt: `def average(numbers):\n    total = sum(numbers)\n    return total / count`,
    prompt: "Which variable should divide the total?",
    choices: ["len(numbers)", "total", "sum", "average"],
    answer: "len(numbers)",
    hint: "Divide by how many numbers are in the list.",
    example: `numbers = [2, 4]\nlen(numbers)  # 2`,
    explanation:
      "The list length is the count of numbers, so it is the useful divisor.",
    recap: "Use the collection's length when finding an average.",
    actionLabel: "Water the average tree",
    beforeCode: `return total / count`,
    afterCode: `return total / len(numbers)`,
    proposedFix: "Divide by `len(numbers)`.",
    reanalysisEvidence: "The undefined-count finding is removed.",
  },
  "py-medium-02": {
    findingId: "py-medium-02",
    difficulty: "medium",
    gradeBand: medium,
    questionType: "execute-it",
    language: "python",
    codeExcerpt: `def is_even(number):\n    return number % 2 = 0`,
    prompt: "Which operator compares the remainder to zero?",
    choices: ["==", "=", "+=", "=>"],
    answer: "==",
    hint: "One equals stores; two equals compares.",
    example: `number % 2 == 0`,
    explanation:
      "The double-equals operator asks whether two values are equal.",
    recap: "Use == for comparison and = for assignment.",
    actionLabel: "Tend the comparison bush",
    beforeCode: `return number % 2 = 0`,
    afterCode: `return number % 2 == 0`,
    proposedFix: "Replace assignment with comparison.",
    reanalysisEvidence: "The comparison-syntax finding is resolved.",
  },
  "py-medium-03": {
    findingId: "py-medium-03",
    difficulty: "medium",
    gradeBand: medium,
    questionType: "find-it",
    language: "python",
    codeExcerpt: `def repeat(word, times):\n    return word * time`,
    prompt: "Which spelling matches the parameter?",
    choices: ["times", "time", "repeat", "word"],
    answer: "times",
    hint: "Read the names inside the parentheses.",
    example: `def repeat(word, times):\n    return word * times`,
    explanation:
      "The parameter is named `times`, so the body must use that exact name.",
    recap: "Function arguments must use their declared names.",
    actionLabel: "Prune the argument mix-up",
    beforeCode: `return word * time`,
    afterCode: `return word * times`,
    proposedFix: "Use the declared argument name.",
    reanalysisEvidence: "The undefined-argument finding disappears.",
  },
  "py-medium-04": {
    findingId: "py-medium-04",
    difficulty: "medium",
    gradeBand: medium,
    questionType: "plan-it",
    language: "python",
    codeExcerpt: `import math\nprint(math.squrt(9))`,
    prompt: "Which function name is spelled correctly?",
    choices: ["sqrt", "squrt", "square", "root"],
    answer: "sqrt",
    hint: "The math module's square-root function is short.",
    example: `import math\nmath.sqrt(9)`,
    explanation:
      "The imported module provides `sqrt`; the misspelled name does not exist.",
    recap: "Imported names must be spelled exactly.",
    actionLabel: "Water the import seedling",
    beforeCode: `print(math.squrt(9))`,
    afterCode: `print(math.sqrt(9))`,
    proposedFix: "Correct the imported function name.",
    reanalysisEvidence: "The missing-attribute finding is cleared.",
  },
  "py-medium-05": {
    findingId: "py-medium-05",
    difficulty: "medium",
    gradeBand: medium,
    questionType: "execute-it",
    language: "python",
    codeExcerpt: `total = 0\nfor value in values:\n    total = value`,
    prompt: "What keeps adding each value to the total?",
    choices: ["total += value", "total = value", "value = total", "total++"],
    answer: "total += value",
    hint: "The total should remember what it already has.",
    example: `total = 0\nfor value in [1, 2]:\n    total += value`,
    explanation:
      "Adding to the existing total keeps every earlier value instead of replacing it.",
    recap: "Use += to grow a running total.",
    actionLabel: "Tend the running-total tree",
    beforeCode: `total = value`,
    afterCode: `total += value`,
    proposedFix: "Add each value to the existing total.",
    reanalysisEvidence: "The broken-accumulation finding is resolved.",
  },
  "py-hard-01": {
    findingId: "py-hard-01",
    difficulty: "hard",
    gradeBand: hard,
    questionType: "plan-it",
    language: "python",
    codeExcerpt: `def safe_divide(a, b):\n    return a / b`,
    prompt: "What should the function handle before dividing?",
    choices: [
      "b == 0",
      "a is a string",
      "the file is short",
      "the answer is pretty",
    ],
    answer: "b == 0",
    hint: "Which input makes division impossible?",
    example: `if b == 0:\n    return None`,
    explanation:
      "Checking for zero prevents a division-by-zero error before the operation runs.",
    recap: "Check dangerous inputs before using them.",
    actionLabel: "Protect the division tree",
    beforeCode: `return a / b`,
    afterCode: `if b == 0:\n        return None\n    return a / b`,
    proposedFix: "Handle a zero denominator first.",
    reanalysisEvidence: "The unsafe-division finding is removed.",
  },
  "py-hard-02": {
    findingId: "py-hard-02",
    difficulty: "hard",
    gradeBand: hard,
    questionType: "execute-it",
    language: "python",
    codeExcerpt: `items = []\nfor item in items:\n    if item.active:\n        active.append(item)`,
    prompt: "What must exist before append is used?",
    choices: ["active = []", "items = 1", "active = None", "nothing"],
    answer: "active = []",
    hint: "The destination list needs to be created first.",
    example: `active = []\nactive.append("plant")`,
    explanation:
      "Creating an empty list gives the loop a safe place to collect active items.",
    recap: "Initialize a collection before adding to it.",
    actionLabel: "Plant the collection bed",
    beforeCode: `items = []\nfor item in items:\n    active.append(item)`,
    afterCode: `items = []\nactive = []\nfor item in items:\n    active.append(item)`,
    proposedFix: "Initialize `active` before the loop.",
    reanalysisEvidence: "The undefined-list finding is cleared.",
  },
  "py-hard-03": {
    findingId: "py-hard-03",
    difficulty: "hard",
    gradeBand: hard,
    questionType: "find-it",
    language: "python",
    codeExcerpt: `def clean_name(name):\n    return name.strip.lower()`,
    prompt: "Which call actually removes spaces and lowercases text?",
    choices: [
      "name.strip().lower()",
      "name.strip.lower",
      "name.lower.strip",
      "strip(name)",
    ],
    answer: "name.strip().lower()",
    hint: "Each method needs parentheses when you call it.",
    example: `" Ada ".strip().lower()`,
    explanation:
      "Calling strip first and then lower makes a clean lowercase value.",
    recap: "Call each method with parentheses in the right order.",
    actionLabel: "Trim the method hedge",
    beforeCode: `return name.strip.lower()`,
    afterCode: `return name.strip().lower()`,
    proposedFix: "Call both string methods.",
    reanalysisEvidence: "The method-call finding is resolved.",
  },
  "py-hard-04": {
    findingId: "py-hard-04",
    difficulty: "hard",
    gradeBand: hard,
    questionType: "plan-it",
    language: "python",
    codeExcerpt: `def first_item(items):\n    if items:\n        return items[0]\n    return items[0]`,
    prompt: "What should happen when the list is empty?",
    choices: [
      "Return None",
      "Read items[0] anyway",
      "Loop forever",
      "Delete the function",
    ],
    answer: "Return None",
    hint: "An empty list has no item at position zero.",
    example: `if not items:\n    return None`,
    explanation:
      "A safe empty-list branch avoids indexing before an item exists.",
    recap: "Handle the empty case before indexing.",
    actionLabel: "Water the empty-case tree",
    beforeCode: `return items[0]`,
    afterCode: `if not items:\n        return None\n    return items[0]`,
    proposedFix: "Return a safe value when the list is empty.",
    reanalysisEvidence: "The empty-input finding is cleared.",
  },
  "py-hard-05": {
    findingId: "py-hard-05",
    difficulty: "hard",
    gradeBand: hard,
    questionType: "execute-it",
    language: "python",
    codeExcerpt: `def count_down(number):\n    while number > 0:\n        print(number)`,
    prompt: "What changes the value so this loop can finish?",
    choices: ["number -= 1", "number = number", "print(number)", "while False"],
    answer: "number -= 1",
    hint: "The loop condition must eventually become false.",
    example: `while number > 0:\n    number -= 1`,
    explanation:
      "Subtracting one each time moves number toward zero so the loop stops.",
    recap: "A loop needs progress toward its stopping condition.",
    actionLabel: "Mow the endless loop",
    beforeCode: `while number > 0:\n    print(number)`,
    afterCode: `while number > 0:\n        print(number)\n        number -= 1`,
    proposedFix: "Decrease the loop value each pass.",
    reanalysisEvidence: "The endless-loop finding is resolved.",
  },
} as unknown as Record<string, TeachingQuestionContent>;

for (const content of Object.values(teachingQuestionContent)) {
  teachingQuestionContentSchema.parse(content);
  content.answers = [content.answer];
}

export const easyQuestionIds = Object.values(teachingQuestionContent)
  .filter((question) => question.difficulty === "easy")
  .map((question) => question.findingId);
export const mediumQuestionIds = Object.values(teachingQuestionContent)
  .filter((question) => question.difficulty === "medium")
  .map((question) => question.findingId);
export const hardQuestionIds = Object.values(teachingQuestionContent)
  .filter((question) => question.difficulty === "hard")
  .map((question) => question.findingId);

export function activeQuestionIdsForDifficulty(
  difficulty: "easy" | "medium" | "hard",
  random = Math.random,
) {
  const pool =
    difficulty === "easy"
      ? easyQuestionIds
      : difficulty === "medium"
        ? mediumQuestionIds
        : hardQuestionIds;
  if (difficulty !== "easy") return [...pool];
  // The ten Easy questions are paired by garden target. Pick one from each
  // pair so the random session still opens exactly five visible targets.
  return Array.from({ length: 5 }, (_, index) =>
    pool[index + (random() < 0.5 ? 0 : 5)],
  );
}
